### ISSUE TITLE
node-resemble cannot see the difference of two images

### ISSUE THREAD

**Issue by yiqunliang** [lksv/node-resemble.js#35] opened 2017-03-20 06:27 UTC
I use CSS regression testig in WebdriverIO solution to test one of our Web product. There is a color change for one close icon, but seems node-resemble cannot see the difference, the comparing result is still passed.

![pic-1](https://cloud.githubusercontent.com/assets/26535965/24090219/2106e0e2-0d79-11e7-930f-b48655baf04d.png)
![pic-2](https://cloud.githubusercontent.com/assets/26535965/24090220/22bc48d2-0d79-11e7-8fd4-bedb5a8b87dc.png)

**Comment by mirzazeyrek** [comment] 2017-03-20 07:28
Hello yiqunliang,

I have tried the code in the examples and I couldn't reproduce the issue. Here is the created diff image:

![issue-diff](https://cloud.githubusercontent.com/assets/6233650/24091187/319fa67a-0d4f-11e7-82e4-5f0bc7aef6ac.png)

I have copied the files you attached as issue-1.png and issue-2.png and changed the code in the example/example.js folder: 

var resemble = require('../resemble.js');
var fs = require('fs');

resemble.outputSettings({
  errorColor: {
    red: 155,
    green: 100,
    blue: 155
  },
  errorType: 'movement',
  transparency: 0.6
});

resemble('issue-1.png').compareTo('issue-2.png')
  .onComplete(function(data){
    console.log(data);
    data.getDiffImage().pack().pipe(fs.createWriteStream('issue-diff.png'));
  });`

It seems like issue is related with your code. Did you changed something regarding to misMatchPercentage ?

**Comment by yiqunliang** [comment] 2017-03-20 11:17
Hi mirzazeyrek,

I tried your steps, yes the diff file was created.
However in my real case there is no diff file created. Then I try to update the config.js file, update the misMatchTolerance from 0 to 0.0001 then the diff file is created.
I don't know why value 0 doesn't work. 
And thanks for your inspiration.

// config the webdrivercss folder
function getWebdrivercss(fileName){

	var folderPath={
		webdrivercss:
		{
			screenshotRoot: './screenshots/'+'/'+fileName+'/',
			failedComparisonsRoot: './failures/'+'/'+fileName+'/',
			misMatchTolerance: 0.0001,
			screenWidth: 1600

		}
	}
	return folderPath.webdrivercss
}

**Comment by mirzazeyrek** [comment] 2017-03-20 11:44
Oh, glad to see that issue is resolved :) 

Closing this since it doesn't look like a bug but a feature.

**Closed by mirzazeyrek** 2017-03-20 11:44 UTC
